<a href="https://colab.research.google.com/github/PhiDo144/vietnam-typhoon-risk-model/blob/main/Vietnam_typhoon_climate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
gio = 200
mua = 300
tai_san = 10000
he_so_bdkh = 1.1

print("Tốc độ gió là:", gio)

Tốc độ gió là: 200

In [2]:
if gio > 150:
      P = 0.05
else:
      P = 0.20

print("Xác suất P là:", P)

Xác suất P là: 0.05

In [3]:
import pandas as pd

# Tạo bảng gồm 2 trận bão (Quảng Ninh & Hà Nội)
data = {
    'Tinh': ['Quảng Ninh', 'Hà Nội'],
    'Wind': [200, 100],
    'Rain': [300, 150]
            }
df = pd.DataFrame(data)
df # In bảng ra xem

         Tinh  Wind  Rain
0  Quảng Ninh   200   300
1      Hà Nội   100   150

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Thiết lập giao diện biểu đồ và cố định ngẫu nhiên để kết quả không đổi
sns.set_theme(style="whitegrid")
np.random.seed(42)

# Khai báo số lượng bão và danh sách các tỉnh
n_events = 200
provinces = ['Quảng Ninh', 'Hải Phòng', 'Thái Bình', 'Nam Định', 'Hà Nội', 'Lạng Sơn']

print("Đã khởi tạo xong thư viện và thông số cơ bản!")

Đã khởi tạo xong thư viện và thông số cơ bản!

In [5]:
# Tạo dictionary chứa dữ liệu ngẫu nhiên
data = {
    'Event_ID': [f'TY_{i:03d}' for i in range(n_events)],
        'Province': np.random.choice(provinces, size=n_events),
            'Wind_Speed_Kmh': np.random.uniform(80, 230, size=n_events),       # Gió: 80 - 230 km/h
                'Rainfall_mm': np.random.uniform(100, 600, size=n_events),         # Mưa: 100 - 600 mm
                    'Exposure_Value_Billion_VND': np.random.uniform(5000, 50000, size=n_events), # Tài sản: 5k - 50k tỷ
                        'Climate_Change_Factor': np.random.uniform(1.0, 1.3, size=n_events) # Hệ số BĐKH: 1.0 - 1.3
                        }
# Chuyển dictionary thành Bảng dữ liệu (DataFrame)
f = pd.DataFrame(data)

# In 5 dòng đầu tiên của bảng ra xem thử
df.head()

         Tinh  Wind  Rain
0  Quảng Ninh   200   300
1      Hà Nội   100   150

In [6]:
# 1. Khai báo biến đầu vào (Ví dụ)
gio = 150            # Tốc độ gió (km/h)
mua = 300            # Lượng mưa (mm)
he_so_bdkh = 1.2      # Hệ số biến đổi khí hậu
tai_san = 500        # Giá trị tài sản (Tỷ VNĐ)
P = 0.05             # Xác suất xảy ra thiên tai (5% = 0.05)

# 2. Tính tỷ lệ thiệt hại và khống chế trần tối đa 100% (1.0)
raw_damage_rate = (((gio / 250)**2 * 0.5) + ((mua / 600) * 0.5)) * he_so_bdkh
damage_rate = min(1.0, raw_damage_rate)  # Giới hạn tối đa 100%

# 3. Tính thiệt hại thực tế C
C = tai_san * damage_rate

# 4. Tính rủi ro kỳ vọng E(Risk)
E_Risk = P * C

# 5. In kết quả chuẩn định dạng
print(f"Tỷ lệ thiệt hại: {damage_rate * 100:.2f}%")
print(f"Thiệt hại thực tế C: {C:.2f} Tỷ")
print(f"Rủi ro kỳ vọng E(Risk): {E_Risk:.4f} Tỷ")

Tỷ lệ thiệt hại: 51.60%
Thiệt hại thực tế C: 258.00 Tỷ
Rủi ro kỳ vọng E(Risk): 12.9000 Tỷ